# vim: ft=sh:

if [ -e ~/.bashrc ]; then
  source ~/.bashrc
fi

if [ -e ~/.bash_aliases ]; then
  source ~/.bash_aliases
fi

FORTUNES='dune mars-trilogy stoicism ursula tyson sagan dispossessed freedom engineering'

if which fortune > /dev/null; then
  echo "________________________________________________________________________________"
  echo
  fortune $FORTUNES
  echo "________________________________________________________________________________"
  echo
fi

source "$HOME/.cargo/env"
