#!/usr/bin/env python

import os
import time
from glob import glob
from stat import ST_MTIME

SKIP_FILES = [
    'flush',
    'gemsets.default.gems',
    'zshrc'
]

def install_path(file):
    return os.path.join(os.path.expanduser('~'), "." + file)

def files_to_flush(path):
    return (os.path.isfile(path) and path not in SKIP_FILES)

def isinstalled(file):
    f_path = install_path(file)
    return os.path.isfile(f_path)

if __name__ == '__main__':
    files = filter(files_to_flush, glob('*'))

    for f in files:
        if isinstalled(f):
            print "'%s' is installed in ~/." % f
            
            _ipth = install_path(f)
            _its  = os.stat(_ipth)[ST_MTIME]
            _imts = time.ctime(os.path.getmtime(_ipth))
            print "[installed] '%s' last modified in %s (%s)" % (_ipth, _imts, _its)
            
            _ts  = os.stat(f)[ST_MTIME]
            _mts = time.ctime(os.path.getmtime(f))
            print "[upstream] '%s' last modified in %s (%s)" % (f, _mts, _ts)
            print
        else:
            print "'%s' not found in ~" % f
            print

# vim: ft=python

